#!/bin/ksh
# check-hygiene.sh — two questions about a box, answered with the noise filtered.
#
#   doas ksh scripts/check-hygiene.sh
#
# 1. Permission and ownership drift against mtree's whole-system spec.
#    `/etc/mtree/special` covers /etc, /root, /usr and /var, and is root-only, so
#    both `-f` and `-p /` are needed: the spec's paths are rooted at /, and passing
#    `-p /etc` makes every spec path report as missing and every real file as
#    extra, which is a very long list that means nothing. Even run correctly,
#    mtree calls every file it does not already know about `extra`, and on a box
#    with a mail stack that is most of /etc. The differences worth reading are
#    mode, uid, gid, type, size and link, so those are the only ones printed.
#
#    The daily security(8) mail runs the same comparison, which is the automatic
#    version of this. This is the one to run when you want the answer now.
#
# 2. Whether this box's address is on the blocklists, and which list said so.
#    Spamhaus Zen refuses shared resolvers, and every resolver a Hetzner box is
#    handed is one, so it answers 127.255.255.254 to this box and to a public
#    resolver alike. That is a refusal rather than a listing: a listing is 127.0.0.x
#    and its last octet names the matching list. So the check asks a list of zones,
#    takes the first that gives a verdict, and names it, because a clean answer from
#    SpamCop is a fact about SpamCop and not about Spamhaus. Both this and
#    abuse-monitor.sh go through dnsbl_verdict in lib.sh, so they cannot drift.
#
# 3. Whether a cron job can reach the tools the cron jobs need. cron(8) hands
#    jobs PATH=/usr/bin:/bin, packages live in /usr/local and ifconfig in /sbin,
#    so a job whose PATH is not restored finds neither. abuse-monitor.sh's
#    Healthchecks ping is `curl ... || true`, which makes that look like a clean
#    run: the box reads as monitored while nothing is sent. This section sources
#    /root/.kyriakon-env on cron's PATH and asks what a job would find.
#
# 4. Whether the finger service is intact. It is served by fingerd under inetd
#    from a generated page, so the failure worth catching is a half-configured
#    one: a page carrying no endpoints, a missing provider, or an inetd line that
#    was never added. Each of those leaves port 79 either dark or answering with
#    the wrong thing, and none of them is visible from the box being up. The page
#    is regenerated by every mail deploy, so a stale list only follows a hand edit
#    to httpd.conf or gmid.conf.
#
# Read-only. Exits non-zero when something is wrong, so cron could run it, though
# the daily mail already covers the permissions half.

set -euo pipefail

# cron(8) jobs are given PATH=/usr/bin:/bin, and packages live in /usr/local while
# ifconfig lives in /sbin. Whether this file is run by hand or by cron, put them
# back, for the reason section 3 exists.
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:$PATH"
export PATH

script_dir="$(dirname "$0")"
if [ ! -f "$script_dir/lib.sh" ]; then
	printf '%s: lib.sh is not in %s. Install the two files together, as lib.sh describes.\n' \
		"$0" "$script_dir" >&2
	exit 1
fi

# shellcheck disable=SC1091 # lib.sh resolves at runtime from this script's dir
. "$script_dir/lib.sh"

status=0

# --- 1. permission and ownership drift -----------------------------------
if [ "$(id -u)" -eq 0 ]; then
	drift=$(mtree -q -f /etc/mtree/special -p / 2>&1 \
		| grep -E '^(mode|uid|gid|type|size|link)' || true)
	if [ -n "$drift" ]; then
		printf 'permissions: drift from /etc/mtree/special\n%s\n' "$drift"
		status=1
	else
		printf 'permissions: no drift from /etc/mtree/special\n'
	fi
else
	printf 'permissions: skipped, needs root to read /etc/mtree/special\n'
fi

# --- 2. blocklist --------------------------------------------------------
ip="${PUBLIC_IP:-$(ifconfig egress inet 2>/dev/null | awk '/inet / { print $2; exit }')}"
if [ -z "$ip" ]; then
	printf 'blocklist: cannot determine this box address\n'
	exit "$status"
fi
verdict=$(dnsbl_verdict "$ip")
case "$verdict" in
listed*)
	printf 'blocklist: %s is listed: %s. That names the list and the code; look it up and request removal\n' \
		"$ip" "${verdict#listed }"
	status=1
	;;
clean*)
	printf 'blocklist: %s is not listed on %s\n' "$ip" "${verdict#clean }"
	;;
*)
	printf 'blocklist: %s. A listing would go unnoticed until one answers\n' "$verdict"
	status=1
	;;
esac

# Which resolver answered is worth knowing on its own: Spamhaus, the list that matters
# for deliverability, only answers one that serves a single machine, so its absence
# silently downgrades the verdict to a weaker zone rather than failing the check.
if dig +short +time=2 +tries=1 @127.0.0.1 . NS >/dev/null 2>&1; then
	printf 'blocklist: asked through the resolver on this box, which Spamhaus answers\n'
else
	printf 'blocklist: no resolver on this box, so Spamhaus refuses and the fallback zones carry the verdict. unbound ships in base\n'
fi

# --- 3. does the cron environment still reach the tools cron needs? ------
# cron(8) gives jobs PATH=/usr/bin:/bin. Packages live in /usr/local and ifconfig
# in /sbin, so a job that does not put those back finds neither, and
# abuse-monitor.sh's Healthchecks ping is `curl ... || true`, which turns that
# into a failure indistinguishable from a clean run: the box looks monitored
# while no ping is being sent. Source the env exactly as a cron line does, on
# cron's PATH, and ask what a job would find.
if [ "$(id -u)" -eq 0 ] && [ -f /root/.kyriakon-env ]; then
	absent=""
	tools="curl ifconfig hcloud jq"
	for tool in $tools; do
		env -i PATH=/usr/bin:/bin sh -c ". /root/.kyriakon-env; command -v $tool" >/dev/null 2>&1 \
			|| absent="$absent $tool"
	done
	if [ -n "$absent" ]; then
		printf 'cron environment: a cron job would not find:%s\n' "$absent"
		printf '  the fix is the PATH line in /root/.kyriakon-env, which every cron line sources\n'
		case "$absent" in
		*hcloud*|*jq*) printf '  %s is a package: doas pkg_add %s\n' "$tool" "$tool" ;;
		esac
		status=1
	else
		printf 'cron environment: %s all reachable as a cron job sees them\n' "$tools"
	fi
else
	printf 'cron environment: skipped, needs root and /root/.kyriakon-env\n'
fi

# --- 4. finger -----------------------------------------------------------
# Served by fingerd under inetd from a page the mail deploy generates. Reads
# nothing secret, so this section needs no root guard: the page is world-readable
# by design, since _fingerd is what reads it.
finger_page=/etc/kyriakon/finger.txt
finger_provider=/usr/local/libexec/kyriakon-finger
if [ -f "$finger_page" ] && [ -s "$finger_page" ]; then
	# The endpoint lines are the indented ones, so this is the count that matters
	# rather than the line count. grep -c returns non-zero at zero matches, which
	# under set -e would end the script before it could report the problem.
	endpoints=$(grep -c '^  ' "$finger_page" || true)
	printf 'finger: page present, %s endpoint lines\n' "$endpoints"
	if [ "$endpoints" -eq 0 ]; then
		printf 'finger: the page carries no endpoints; httpd.conf and gmid.conf are the source\n'
		status=1
	fi
else
	printf 'finger: %s missing or empty; the mail deploy installs it\n' "$finger_page"
	status=1
fi
if [ -x "$finger_provider" ]; then
	printf 'finger: provider installed and executable\n'
else
	printf 'finger: %s missing or not executable; port 79 would answer nothing\n' "$finger_provider"
	status=1
fi
# Both families, because inetd takes the socket family from the protocol field and
# a single `tcp` line leaves the IPv6 address refusing connections. Checking only
# that some finger line exists is what let the first version of this ship half-open.
if [ -f /etc/inetd.conf ]; then
	for proto in tcp tcp6; do
		if grep -Eq "^[[:space:]]*finger[[:space:]]+stream[[:space:]]+${proto}[[:space:]]" /etc/inetd.conf; then
			printf 'finger: inetd line present (%s)\n' "$proto"
		else
			printf 'finger: no finger/%s line in /etc/inetd.conf; that family is dark\n' "$proto"
			status=1
		fi
	done
else
	printf 'finger: /etc/inetd.conf is missing; port 79 is dark on both families\n'
	status=1
fi
# --- 5. terraform --------------------------------------------------------
# The repo's one automated path is the weekly restore standup, which now drives the
# Hetzner API with the hcloud CLI and deletes only the server id it created that run. The
# refusals in front of a mistaken destroy are the id discipline in that script, the live
# root's prevent_destroy, and Hetzner's delete_protection. Only the second is checked
# here, because it is the one that lives in a file that can silently lose it.
#
# The path is a variable rather than hardcoded, because the box's checkout is not where
# the repo's own instructions assume and a wrong path reads exactly like a missing guard.
repo_root="${KYRIAKON_REPO:-/root/src/kyriakon-infra}"
tf_dir="$repo_root/terraform"
if grep -q 'prevent_destroy[[:space:]]*=[[:space:]]*true' "$tf_dir/main.tf" 2>/dev/null; then
	printf 'terraform: the live root refuses to plan the removal of its server\n'
else
	printf 'terraform: no prevent_destroy in %s/main.tf; only delete_protection would stand between a bad plan and the mail box\n' "$tf_dir"
	status=1
fi
# The restore image is what the weekly run creates its box from, so an absent or
# mislabelled one means the test cannot run. Checked by looking for the image, which is
# what the standup does too, rather than by trusting a label convention in a document.
# The token lives in the box's env file, which this script does not source into its own
# environment, so it is read the way the cron PATH check reads it: in a subshell that
# sources that file and nothing else.
if [ "$(id -u)" -eq 0 ] && [ -f /root/.kyriakon-env ]; then
	restore_image=$(env -i PATH=/usr/bin:/bin:/usr/local/bin sh -c \
		". /root/.kyriakon-env; hcloud image list -t snapshot -l ${RESTORE_TEST_IMAGE_LABEL:-kind=restore} -o noheader -o columns=id" 2>/dev/null | head -1)
	if [ -n "$restore_image" ]; then
		printf 'terraform: a snapshot labelled %s exists, so the weekly test has a template\n' "${RESTORE_TEST_IMAGE_LABEL:-kind=restore}"
	else
		printf 'terraform: no snapshot labelled %s; the weekly restore test has no template to create from\n' "${RESTORE_TEST_IMAGE_LABEL:-kind=restore}"
		status=1
	fi
else
	printf 'terraform: hcloud and the env file are both needed to check the restore image\n'
	status=1
fi

exit "$status"
