#!/bin/ksh
# check-hygiene.sh — two questions about a box, answered with the noise filtered.
#
#   doas ksh scripts/check-hygiene.sh
#
# 1. Permission and ownership drift against mtree's whole-system spec.
#    `/etc/mtree/special` covers /etc, /root, /usr and /var, and is root-only, so
#    both `-f` and `-p /` are needed: the spec's paths are rooted at /, and passing
#    `-p /etc` makes every spec path report as missing and every real file as
#    extra, which is a very long list that means nothing. Even run correctly,
#    mtree calls every file it does not already know about `extra`, and on a box
#    with a mail stack that is most of /etc. The differences worth reading are
#    mode, uid, gid, type, size and link, so those are the only ones printed.
#
#    The daily security(8) mail runs the same comparison, which is the automatic
#    version of this. This is the one to run when you want the answer now.
#
# 2. Whether this box's address is on Spamhaus Zen. Ask a resolver on the box
#    first, because Spamhaus refuses shared resolvers and every resolver a Hetzner
#    box is handed is one: through those the answer is 127.255.255.254, which
#    looks like a listing and is a refusal. A resolver serving one machine is
#    answered, and 127.0.0.2 to 127.0.0.11 is a real listing whose last octet names
#    the list. The same distinction is in abuse-monitor.sh, which checks every
#    fifteen minutes; keep the two in step if either changes.
#
# 3. Whether a cron job can reach the tools the cron jobs need. cron(8) hands
#    jobs PATH=/usr/bin:/bin, packages live in /usr/local and ifconfig in /sbin,
#    so a job whose PATH is not restored finds neither. abuse-monitor.sh's
#    Healthchecks ping is `curl ... || true`, which makes that look like a clean
#    run: the box reads as monitored while nothing is sent. This section sources
#    /root/.kyriakon-env on cron's PATH and asks what a job would find.
#
# 4. Whether the finger service is intact. It is served by fingerd under inetd
#    from a generated page, so the failure worth catching is a half-configured
#    one: a page carrying no endpoints, a missing provider, or an inetd line that
#    was never added. Each of those leaves port 79 either dark or answering with
#    the wrong thing, and none of them is visible from the box being up. The page
#    is regenerated by every mail deploy, so a stale list only follows a hand edit
#    to httpd.conf or gmid.conf.
#
# Read-only. Exits non-zero when something is wrong, so cron could run it, though
# the daily mail already covers the permissions half.

set -euo pipefail

# cron(8) jobs are given PATH=/usr/bin:/bin, and packages live in /usr/local while
# ifconfig lives in /sbin. Whether this file is run by hand or by cron, put them
# back, for the reason section 3 exists.
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:$PATH"
export PATH

dnsbl_zone="${DNSBL_ZONE:-zen.spamhaus.org}"
status=0

# --- 1. permission and ownership drift -----------------------------------
if [ "$(id -u)" -eq 0 ]; then
	drift=$(mtree -q -f /etc/mtree/special -p / 2>&1 \
		| grep -E '^(mode|uid|gid|type|size|link)' || true)
	if [ -n "$drift" ]; then
		printf 'permissions: drift from /etc/mtree/special\n%s\n' "$drift"
		status=1
	else
		printf 'permissions: no drift from /etc/mtree/special\n'
	fi
else
	printf 'permissions: skipped, needs root to read /etc/mtree/special\n'
fi

# --- 2. blocklist --------------------------------------------------------
ip="${PUBLIC_IP:-$(ifconfig egress inet 2>/dev/null | awk '/inet / { print $2; exit }')}"
if [ -z "$ip" ]; then
	printf 'blocklist: cannot determine this box address\n'
	exit "$status"
fi
rev=$(printf '%s\n' "$ip" | awk -F. '{ print $4"."$3"."$2"."$1 }')
if dig +short +time=2 +tries=1 @127.0.0.1 . NS >/dev/null 2>&1; then
	answer=$(dig +short +time=5 +tries=2 @127.0.0.1 "$rev.$dnsbl_zone" A 2>/dev/null || true)
	via="the resolver on this box"
else
	answer=$(dig +short +time=5 +tries=2 "$rev.$dnsbl_zone" A 2>/dev/null || true)
	via="the system resolver"
fi
case "$answer" in
"")
	printf 'blocklist: %s is not listed on %s (via %s)\n' "$ip" "$dnsbl_zone" "$via"
	;;
127.255.255.*)
	printf 'blocklist: cannot check, %s refuses %s. A resolver on the box is answered and is not refused; unbound ships in base\n' \
		"$dnsbl_zone" "$via"
	status=1
	;;
127.0.0.*)
	printf 'blocklist: %s IS listed on %s as 127.0.0.%s. That code names the list; look it up at check.spamhaus.org\n' \
		"$ip" "$dnsbl_zone" "$(printf '%s\n' "$answer" | head -1 | awk -F. '{ print $4 }')"
	status=1
	;;
*)
	printf 'blocklist: %s gave an unexpected answer: %s\n' "$dnsbl_zone" "$answer"
	status=1
	;;
esac

# --- 3. does the cron environment still reach the tools cron needs? ------
# cron(8) gives jobs PATH=/usr/bin:/bin. Packages live in /usr/local and ifconfig
# in /sbin, so a job that does not put those back finds neither, and
# abuse-monitor.sh's Healthchecks ping is `curl ... || true`, which turns that
# into a failure indistinguishable from a clean run: the box looks monitored
# while no ping is being sent. Source the env exactly as a cron line does, on
# cron's PATH, and ask what a job would find.
if [ "$(id -u)" -eq 0 ] && [ -f /root/.kyriakon-env ]; then
	absent=""
	for tool in curl ifconfig; do
		env -i PATH=/usr/bin:/bin sh -c ". /root/.kyriakon-env; command -v $tool" >/dev/null 2>&1 \
			|| absent="$absent $tool"
	done
	if [ -n "$absent" ]; then
		printf 'cron environment: a cron job would not find:%s\n' "$absent"
		printf '  the fix is the PATH line in /root/.kyriakon-env, which every cron line sources\n'
		status=1
	else
		printf 'cron environment: curl and ifconfig both reachable as a cron job sees them\n'
	fi
else
	printf 'cron environment: skipped, needs root and /root/.kyriakon-env\n'
fi

# --- 4. finger -----------------------------------------------------------
# Served by fingerd under inetd from a page the mail deploy generates. Reads
# nothing secret, so this section needs no root guard: the page is world-readable
# by design, since _fingerd is what reads it.
finger_page=/etc/kyriakon/finger.txt
finger_provider=/usr/local/libexec/kyriakon-finger
if [ -f "$finger_page" ] && [ -s "$finger_page" ]; then
	# The endpoint lines are the indented ones, so this is the count that matters
	# rather than the line count. grep -c returns non-zero at zero matches, which
	# under set -e would end the script before it could report the problem.
	endpoints=$(grep -c '^  ' "$finger_page" || true)
	printf 'finger: page present, %s endpoint lines\n' "$endpoints"
	if [ "$endpoints" -eq 0 ]; then
		printf 'finger: the page carries no endpoints; httpd.conf and gmid.conf are the source\n'
		status=1
	fi
else
	printf 'finger: %s missing or empty; the mail deploy installs it\n' "$finger_page"
	status=1
fi
if [ -x "$finger_provider" ]; then
	printf 'finger: provider installed and executable\n'
else
	printf 'finger: %s missing or not executable; port 79 would answer nothing\n' "$finger_provider"
	status=1
fi
if [ -f /etc/inetd.conf ] && grep -Eq '^[[:space:]]*finger[[:space:]]' /etc/inetd.conf; then
	printf 'finger: inetd line present\n'
else
	printf 'finger: no finger line in /etc/inetd.conf; port 79 is dark\n'
	status=1
fi

exit "$status"
