#!/bin/ksh
# provision-member-capsule.sh: the member's capsule block and the platform pair.
#
# Usage:
#   doas ksh scripts/provision-member-capsule.sh <username>
#        ksh scripts/provision-member-capsule.sh --self-test
#
# Runs ON the box as root, after scripts/provision-member.sh has built the
# member's tree.
#
# What it writes, and why each shape:
#
#   /etc/ssl/capsule-kyriakon.net.cnf             root:wheel 0644
#   /etc/ssl/capsule-kyriakon.net.crt             root:wheel 0644
#   /etc/ssl/private/capsule-kyriakon.net.key     root:wheel 0600
#   /etc/gmid.d/<username>.kyriakon.net.conf      root:wheel 0644
#
# The capsule does not use ACME. One self-signed pair serves kyriakon.net and
# *.kyriakon.net, which covers every capsule this platform runs and every member
# capsule hostname, so no member has an ACME order for a capsule name and no
# expiry arrives to break a reader's pin: the pair is generated once with a
# ten-year life and never renewed. Each capsule block names that pair rather than
# the member's own certificate, which is the one httpd serves over 443.
#
# The pair is generated by openssl req -x509 driven from a configuration file,
# not from command-line extension flags, because the LibreSSL in the base system
# carries the configuration route: -addext and the other flags the OpenSSL 3
# command line has are not there. The configuration file is written by this
# script rather than checked in, so the invocation and the extensions it asks for
# cannot drift apart, and the runbook's regeneration step is the same invocation.
# A pair that is lost is generated again by running this script: the step is never
# automated, because the fingerprint the help page publishes only changes when a
# human runs it.
#
# It is generated once. A run that finds both halves does not touch them, because
# a regeneration is not free: every reader's gemini client pins the certificate on
# first use, so a new pair is a prompt for every capsule at once, and the
# fingerprint the help page publishes has to be updated by hand. A run that finds
# one half missing generates both and says so, because half a pair serves nothing.
#
# The member's block is one server on port 1965 with the member's gemini root,
# the .git block, and the pair. gmid chroots to /home/www, so root
# "/<name>.kyriakon.net/gemini" is /home/www/<name>.kyriakon.net/gemini, which is
# the member's own tree, and the cert and key paths stay absolute because
# gmid.conf(5) makes those two the exceptions to the chroot rule. The .git block
# is there because a member's gemini root is a checkout they upload over sftp:
# without it the capsule would serve the whole history, including anything deleted
# from the working tree.
#
# The index and the reload are not this script's job. /etc/gmid.d/index.conf is
# regenerated and gmid is checked with gmid -n and then reloaded by
# scripts/cron-apply.sh --web, which does it once for every member file at once.
#
# Env: none. The self-test rebinds this script's own paths to a throwaway tree
# under TMPDIR, so it needs no root and touches nothing outside it.
#
# Not this script's job: the member's tree (scripts/provision-member.sh), the
# member's own certificate (the ACME lane, #289), the index, the reload, or the
# httpd vhost for the same name (scripts/provision-member-web.sh). An own-domain
# capsule gets its own pair, which the own-domain tier owns (#314).

set -euo pipefail

# The private key half is created under this umask, so a key file that openssl
# creates is never readable by anyone else even for the moment before the chmod
# below runs.
umask 077

# The base system's LibreSSL, which is the openssl the runbook's step and this
# script agree on. Named in full rather than looked up on PATH because a package
# openssl in /usr/local is a different parser and this invocation is written for
# the one in base.
openssl=/usr/bin/openssl

gmid_d=/etc/gmid.d
ssl_dir=/etc/ssl
ssl_private=/etc/ssl/private
public_root=/home/www
conf_owner="root:wheel"

usage() {
	cat >&2 <<'USAGE'
usage: doas ksh provision-member-capsule.sh <username>
       ksh scripts/provision-member-capsule.sh --self-test
USAGE
	exit 2
}

die() {
	printf 'provision-member-capsule: %s\n' "$*" >&2
	exit 1
}

# The name, and the same charset rule add-user.sh and provision-member.sh apply.
name_ok() {
	printf '%s' "$1" | grep -Eq '^[a-z0-9][a-z0-9._-]{0,31}$'
}

# The paths, as functions rather than variables so the self-test rebinds the
# directories once and every caller follows.
capsule_cnf() { printf '%s/capsule-kyriakon.net.cnf' "$ssl_dir"; }
capsule_cert() { printf '%s/capsule-kyriakon.net.crt' "$ssl_dir"; }
capsule_key() { printf '%s/capsule-kyriakon.net.key' "$ssl_private"; }
member_conf() { printf '%s/%s.kyriakon.net.conf' "$gmid_d" "$user"; }

# --- the pair ----------------------------------------------------------------

# The extension requests, and why each: the two names every capsule answers on,
# and an end-entity certificate rather than a CA, marked critical so a client
# cannot read it as one that may sign.
capsule_cnf_body() {
	cat <<'EOF'
# The extension requests for the platform's capsule pair. Written by
# scripts/provision-member-capsule.sh, which is the only thing that runs openssl
# on it, so the pair and the requests for it cannot drift apart.
#
# A configuration file rather than command-line extension flags: the LibreSSL in
# the base system carries this route, and the runbook's regeneration step is the
# script that writes this file.

[ req ]
default_bits		= 4096
default_md		= sha256
distinguished_name	= subject
prompt			= no
x509_extensions		= capsule

[ subject ]
CN			= kyriakon.net

[ capsule ]
subjectAltName		= DNS:kyriakon.net, DNS:*.kyriakon.net
basicConstraints	= critical, CA:FALSE
EOF
}

pair_present() {
	[ -f "$(capsule_cert)" ] && [ -f "$(capsule_key)" ]
}

write_capsule_cnf() {
	typeset target candidate
	target=$(capsule_cnf)
	candidate="$target.new.$$"
	capsule_cnf_body > "$candidate"
	if [ -f "$target" ] && cmp -s "$candidate" "$target"; then
		rm -f "$candidate"
		return 0
	fi
	chmod 0644 "$candidate"
	mv "$candidate" "$target"
	printf 'capsule pair: %s written\n' "$target"
	return 0
}

ensure_capsule_pair() {
	typeset cert key generated fingerprint

	cert=$(capsule_cert)
	key=$(capsule_key)

	# The requests are kept in step with the script that runs openssl, so a
	# generation always uses the extensions this version asks for, whether it is the
	# first one or a repair.
	write_capsule_cnf

	if pair_present; then
		printf 'capsule pair: %s already holds both halves, left alone\n' "$cert"
		return 0
	fi

	# Generating over one half of a pair is not a repair: the two halves are one
	# certificate, so a missing key means a new pair, and a new pair is a prompt for
	# every capsule's readers. Say that where it happens rather than in a runbook.
	generated=no
	if [ -e "$cert" ] || [ -e "$key" ]; then
		printf 'capsule pair: only one half was there, so the pair is regenerated.\n'
		printf '  Every reader trusts the new certificate once, and the fingerprint the\n'
		printf '  help page publishes has to be updated: docs/runbook.md, "Regenerate the\n'
		printf '  capsule certificate pair".\n' >&2
		generated=yes
	fi

	write_capsule_cnf

	if ! "$openssl" req -x509 -new -nodes -days 3650 -config "$(capsule_cnf)" \
		-keyout "$key" -out "$cert"; then
		die "$openssl req failed; $cert and $key may be half written, remove both and run this again"
	fi
	chmod 0644 "$cert"
	chmod 0600 "$key"

	# The pair is the thing every capsule is served from, so it is checked here as
	# well as in the self-test: present, non-empty, and parseable. What it covers is
	# asserted in the self-test, where the extension text is this openssl's.
	for f in "$cert" "$key"; do
		[ -s "$f" ] || die "$f is empty after the generation step"
	done
	"$openssl" x509 -in "$cert" -noout >/dev/null 2>&1 \
		|| die "$cert does not parse as a certificate"
	[ "$(stat -f '%Lp' "$key")" = 600 ] || die "$key is not mode 0600"

	if [ "$generated" = no ]; then
		printf 'capsule pair: generated at %s (ten years, kyriakon.net and *.kyriakon.net)\n' "$cert"
	fi
	# The fingerprint and the date it changed, which is what the help page carries.
	# Printed because a human pastes it there: nothing regenerates the pair on a
	# schedule, so nothing else can publish it.
	fingerprint=$("$openssl" x509 -in "$cert" -noout -fingerprint -sha256 | sed 's/^.*=//')
	printf 'capsule fingerprint (help page): %s, changed %s\n' "$fingerprint" "$(date +%Y-%m-%d)"
	return 0
}

# --- the member's block ------------------------------------------------------

member_conf_body() {
	printf 'server "%s.kyriakon.net" {\n' "$user"
	printf '\tlisten on * port 1965\n'
	printf '\n'
	printf '\tcert "%s"\n' "$(capsule_cert)"
	printf '\tkey "%s"\n' "$(capsule_key)"
	printf '\n'
	printf '\troot "/%s.kyriakon.net/gemini"\n' "$user"
	printf '\n'
	printf '\tlocation "/.git/*" {\n'
	printf '\t\tblock\n'
	printf '\t}\n'
	printf '}\n'
}

# write_member_conf: the file, rewritten only when it would differ. Sets
# conf_changed for the caller.
write_member_conf() {
	typeset target candidate
	target=$(member_conf)
	candidate="$target.new.$$"
	if ! member_conf_body > "$candidate"; then
		rm -f "$candidate"
		exit 1
	fi
	if [ -f "$target" ] && cmp -s "$candidate" "$target"; then
		rm -f "$candidate"
		conf_changed=no
		printf '%s: unchanged\n' "$target"
		return 0
	fi
	chmod 0644 "$candidate"
	mv "$candidate" "$target"
	conf_changed=yes
	printf 'wrote %s: %s.kyriakon.net on 1965 from %s\n' \
		"$target" "$user" "$(capsule_cert)"
}

assert_member_conf() {
	typeset target shape
	target=$(member_conf)
	[ -f "$target" ] || die "$target is not there after writing it"
	shape=$(stat -f '%Su:%Sg %Lp' "$target")
	[ "$shape" = "$conf_owner 644" ] || die "$target is $shape, wanted $conf_owner 644"
}

# The tree the block's root names, which provision-member.sh builds.
assert_member_tree() {
	typeset public
	public="$public_root/$user.kyriakon.net"
	[ -d "$public" ] || die "no $public: run scripts/provision-member.sh $user first"
	[ -d "$public/gemini" ] || die "no $public/gemini: run scripts/provision-member.sh $user first"
}

# --- self-test ---------------------------------------------------------------
#
# The file generation and the pair are the whole of this script's risk, so both
# are exercised here against a throwaway tree, with the real openssl: the block's
# shape, a second run that changes nothing, and a pair that carries the two names,
# an end-entity constraint and about ten years. Runs as anyone, writes only under
# TMPDIR.

self_test() {
	typeset tree fails conf before out
	tree=$(mktemp -d "${TMPDIR:-/tmp}/provision-member-capsule.XXXXXX")
	# Script scope, so the EXIT trap still sees it: a function's typeset name is
	# gone by then, and set -u turns that into a line on stderr and a non-zero exit
	# on a run where every check passed.
	self_test_work="$tree"
	trap 'rm -rf "$self_test_work"' EXIT
	fails=0
	check() {
		if [ "$2" = "$3" ]; then
			printf '  ok   %s\n' "$1"
		else
			printf '  FAIL %s: expected [%s], got [%s]\n' "$1" "$3" "$2"
			fails=$((fails + 1))
		fi
	}

	gmid_d="$tree/etc/gmid.d"
	ssl_dir="$tree/etc/ssl"
	ssl_private="$ssl_dir/private"
	public_root="$tree/home/www"
	user=alice
	install -d -m 0755 "$gmid_d" "$ssl_private" "$public_root/alice.kyriakon.net/gemini"
	# A new file takes its directory's group on this box, and in a throwaway tree
	# that is the tree's owner rather than wheel, so the group comes from the
	# directory the file lands in. On the box it is root:wheel, which is what
	# assert_member_conf checks in the production path.
	conf_owner="$(id -un):$(stat -f '%Sg' "$gmid_d")"

	conf=$(member_conf)

	# 1. the member's block
	write_member_conf >/dev/null
	check "the server is the member's name" "$(awk 'NR == 1' "$conf")" 'server "alice.kyriakon.net" {'
	check "it listens on the gemini port" "$(grep -c 'listen on \* port 1965' "$conf")" 1
	check "it names the capsule certificate" "$(grep -cF "cert \"$ssl_dir/capsule-kyriakon.net.crt\"" "$conf")" 1
	check "and the capsule key" "$(grep -cF "key \"$ssl_private/capsule-kyriakon.net.key\"" "$conf")" 1
	check "the root is the member's gemini tree" "$(grep -c 'root "/alice.kyriakon.net/gemini"' "$conf")" 1
	check ".git is blocked" "$(grep -c 'location "/.git/\*"' "$conf")" 1
	check "one server block exactly" "$(grep -c '^server ' "$conf")" 1
	check "the file is mode 644 and the writer's" "$(stat -f '%Su:%Sg %Lp' "$conf")" "$conf_owner 644"
	assert_member_conf
	# Printed once, so this check's output carries the file it asserts about: the
	# lines above are what was written, not a description of it.
	printf '\n%s:\n' "$conf"
	cat "$conf"
	printf '\n'

	# 2. the same again: nothing rewritten
	before=$(stat -f '%i %m' "$conf")
	write_member_conf > "$tree/again.out"
	check "a second run leaves the file alone" "$(stat -f '%i %m' "$conf")" "$before"
	check "and says so" "$(grep -c ': unchanged$' "$tree/again.out")" 1

	# 3. the pair, generated once by the script itself
	check "there is no pair to begin with" "$(pair_present && echo yes || echo no)" no
	out=$(ensure_capsule_pair)
	check "the pair exists afterwards" "$(pair_present && echo yes || echo no)" yes
	check "the key is mode 0600" "$(stat -f '%Lp' "$(capsule_key)")" 600
	check "the certificate is mode 0644" "$(stat -f '%Lp' "$(capsule_cert)")" 644
	check "it carries both names" \
		"$("$openssl" x509 -in "$(capsule_cert)" -noout -text | grep -cF 'DNS:kyriakon.net, DNS:*.kyriakon.net')" 1
	check "it is an end entity, critically" \
		"$("$openssl" x509 -in "$(capsule_cert)" -noout -text | grep -A1 'Basic Constraints' | grep -cF 'critical')" 1
	check "and it says CA:FALSE" \
		"$("$openssl" x509 -in "$(capsule_cert)" -noout -text | grep -cF 'CA:FALSE')" 1
	check "it is still valid in ten years less three days" \
		"$("$openssl" x509 -in "$(capsule_cert)" -noout -checkend $((3650 * 86400 - 3 * 86400)) && echo yes || echo no)" yes
	check "and not in ten years plus three days" \
		"$("$openssl" x509 -in "$(capsule_cert)" -noout -checkend $((3650 * 86400 + 3 * 86400)) && echo yes || echo no)" no
	check "and the run prints the fingerprint for the help page" \
		"$(printf '%s\n' "$out" | grep -c '^capsule fingerprint (help page): [0-9A-F][0-9A-F]:')" 1

	# 4. a second run does not touch the pair, which is the whole point of "once"
	before="$(stat -f '%i %m' "$(capsule_cert)") $(stat -f '%i %m' "$(capsule_key)")"
	out=$(ensure_capsule_pair)
	check "a second run leaves the pair alone" \
		"$(stat -f '%i %m' "$(capsule_cert)") $(stat -f '%i %m' "$(capsule_key)")" "$before"
	check "and says the pair was left alone" "$(printf '%s\n' "$out" | grep -c 'left alone')" 1
	check "and prints no fingerprint" "$(printf '%s\n' "$out" | grep -c 'fingerprint')" 0

	# 5. the configuration file it generated is the one openssl read, and is stable
	check "the configuration asks for the two names" \
		"$(grep -c '^subjectAltName' "$(capsule_cnf)")" 1
	before=$(stat -f '%i %m' "$(capsule_cnf)")
	write_capsule_cnf > "$tree/cnf.out"
	check "a second run leaves the configuration alone" "$(stat -f '%i %m' "$(capsule_cnf)")" "$before"

	# 6. half a pair is regenerated, not served
	rm -f "$(capsule_key)"
	: > "$tree/half.out"
	ensure_capsule_pair > "$tree/half.out" 2>&1
	check "half a pair is rebuilt" "$(pair_present && echo yes || echo no)" yes
	check "and says the help page fingerprint changed" \
		"$(grep -c 'help page publishes has to be updated' "$tree/half.out")" 1

	# 7. a member whose tree is not built is refused rather than served
	user=nobody
	rm -rf "$public_root/nobody.kyriakon.net"
	set +e
	( assert_member_tree ) > "$tree/notree.out" 2>&1
	rc=$?
	set -e
	check "a member with no tree is refused" "$rc" 1
	check "and the refusal names provision-member.sh" \
		"$(grep -c 'scripts/provision-member.sh nobody' "$tree/notree.out")" 1

	if [ "$fails" -eq 0 ]; then
		printf 'self-test: all checks passed\n'
	else
		printf 'self-test: %s failed\n' "$fails" >&2
		exit 1
	fi
}

conf_changed=no

case "${1:-}" in
--self-test)
	[ "$#" -eq 1 ] || usage
	self_test
	;;
"")
	usage
	;;
-*)
	usage
	;;
*)
	[ "$#" -eq 1 ] || usage
	user="$1"
	name_ok "$user" || die "not a member name: $user (lowercase [a-z0-9._-], first character alphanumeric, at most 32 characters)"
	[ "$(id -u)" -eq 0 ] || die "run this with doas: it writes $gmid_d and the pair under $ssl_dir"
	[ -x "$openssl" ] || die "no $openssl"
	[ -d "$gmid_d" ] || die "no $gmid_d: doas ksh scripts/deploy-mail.sh creates it, with the index gmid.conf includes"
	assert_member_tree
	# The pair before the block, so no block is ever written naming a certificate
	# that is not there: gmid -n in the --web pass would refuse to reload for every
	# member at once.
	ensure_capsule_pair
	write_member_conf
	assert_member_conf
	if [ "$conf_changed" = yes ]; then
		printf 'next: doas ksh scripts/cron-apply.sh --web   # regenerate the index, check gmid, reload\n'
	fi
	;;
esac
